INSERT INTO "TW"."Department" ("name") VALUES ('Системной интеграции');
INSERT INTO "TW"."Department" ("name") VALUES ('Систем видеонаблюдения и контроля доступа');
INSERT INTO "TW"."Department" ("name") VALUES ('Электромонтажных работ');
INSERT INTO "TW"."Department" ("name") VALUES ('ПТО');
INSERT INTO "TW"."Department" ("name") VALUES ('Бухгалтерия');
INSERT INTO "TW"."Department" ("name") VALUES ('Снабжения');
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Михаленя Андрей Сергеевич', '1989-02-24', 2, 475.14);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Парфенюк Александр Иванович', '1990-11-19', 2, 535.17);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Тунчик Вадим Геннадьевич', '1992-03-10', 2, 414.26);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Савосин Виталий Юрьевич', '1985-07-24', 1, 535.17);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Пивоварчук Вячеслав Владимирович', '1992-03-14', 1, 454.26);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Былинский Александр Юрьевич', '1987-05-17', 0, 554.22);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Дацкевич Олег Александрович', '1987-09-13', 0, 564.27);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Кондрахин Виталий Юрьевич', '1987-06-24', 0, 524.05);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Семёнов Кирилл Алексеевич', '1992-10-06', 0, 414.05);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Петренко Кирилл Александрович', '1989-09-16', 3, 673.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Тюшкевич Александр Григорьевич', '1984-05-12', 3, 523.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Цедрик Сергей Михайлович', '1958-02-10', 3, 523.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Ливак Андрей Вячеславович', '1974-01-17', 3, 423.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Строкач Елена Владимировна', '1962-12-14', 4, 693.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Селивончик Валенина Александровна', '1969-04-16', 4, 723.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Рябова Александра Сергеевна', '1989-11-18', 5, 533.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Новик Светлана Владимировна', '1985-10-21', 5, 535.45);
INSERT INTO "TW"."Employee" ("full_name", "date_of_birth", "department_id", "salary" ) VALUES ('Иовлев Владимир Леонидович', '1981-05-25', 5, 575.45);